# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = ''' 
($username([@](bold)$hostname) in )[\[$directory\]](bold)
$character '''

right_format = "$git_status$git_branch$git_commit"

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[>](bold green)' 
error_symbol = '[>](bold red)' 

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = true
format = '[$path]($style)[$read_only]($read_only_style)'
style = "bold blue"

[username]
show_always = false
style_user = 'white bold'
format = '[$user]($style)'

[hostname]
ssh_only = true
format = "[$hostname](bold green)"

[git_branch]
format = 'on [\[[$branch(:$remote_branch)]($style)\]](bold)'
style = "bold green"

[git_status]
format = '(\[[$ahead_behind]($style)\](bold) )'
untracked = ''
